# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestwithselenium():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testwithselenium(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(656, 680)
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("Attack des titans")
    self.driver.find_element(By.ID, "genre").click()
    self.driver.find_element(By.ID, "genre").send_keys("Action, Adventure, Comedy")
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("On suit l\'aventure de Eren; Mikassa et Armin dans le bataillon d\'exploration et ayant pour but d\'esterminer tous les titans pour leur liberté")
    self.driver.find_element(By.ID, "type").click()
    self.driver.find_element(By.ID, "type").send_keys("TV")
    self.driver.find_element(By.ID, "producer").click()
    self.driver.find_element(By.ID, "producer").send_keys("Sunrise,Bandai,Visual")
    self.driver.find_element(By.ID, "studio").click()
    self.driver.find_element(By.ID, "studio").send_keys("Toei,Animation")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("Attaque des titans")
    self.driver.find_element(By.ID, "genre").click()
    self.driver.find_element(By.ID, "genre").send_keys("Action, Adventure, Comedy")
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("On suit l\'aventure de Eren; Mikassa et Armin dans le bataillon d\'exploration et ayant pour but d\'esterminer tous les titans pour leur liberté")
    self.driver.find_element(By.ID, "type").click()
    self.driver.find_element(By.ID, "type").send_keys("TV")
    self.driver.find_element(By.ID, "producer").click()
    self.driver.find_element(By.ID, "producer").send_keys("Sunrise,Bandai,Visual")
    self.driver.find_element(By.ID, "studio").click()
    self.driver.find_element(By.ID, "studio").send_keys("Toei,Animation")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("Attaque des titans")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.ID, "type").click()
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.ID, "genre").click()
    self.driver.find_element(By.ID, "genre").send_keys("Action, Adventure, Comedy")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("On suit l\'aventure de Eren; Mikassa et Armin dans le bataillon d\'exploration et ayant pour but d\'esterminer tous les titans pour leur liberté")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.ID, "type").click()
    self.driver.find_element(By.ID, "type").send_keys("TV")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.ID, "producer").click()
    self.driver.find_element(By.ID, "producer").send_keys("Sunrise,Bandai,Visual")
    self.driver.find_element(By.ID, "studio").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.ID, "studio").click()
    self.driver.find_element(By.ID, "studio").send_keys("Toei,Animation")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
