version: '3'

services:
  frontend:
    build: ./my-app
    ports:
      - "3000:3000"
    networks:
      - my-network
  backend:
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - my-network

networks:
  my-network:
