# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    # Test name: test1
    # Step # | name | target | value | comment
    # 1 | open | http://localhost:3000/ |  | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 656x680 |  | 
    self.driver.set_window_size(656, 680)
    # 3 | click | css=form |  | 
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    # 4 | click | id=title |  | 
    self.driver.find_element(By.ID, "title").click()
    # 5 | type | id=title | Attack des titans | 
    self.driver.find_element(By.ID, "title").send_keys("Attack des titans")
    # 6 | click | id=genre |  | 
    self.driver.find_element(By.ID, "genre").click()
    # 7 | type | id=genre | Action, Adventure, Comedy | 
    self.driver.find_element(By.ID, "genre").send_keys("Action, Adventure, Comedy")
    # 8 | click | id=description |  | 
    self.driver.find_element(By.ID, "description").click()
    # 9 | type | id=description | On suit l'aventure de Eren; Mikassa et Armin dans le bataillon d'exploration et ayant pour but d'esterminer tous les titans pour leur liberté | 
    self.driver.find_element(By.ID, "description").send_keys("On suit l\'aventure de Eren; Mikassa et Armin dans le bataillon d\'exploration et ayant pour but d\'esterminer tous les titans pour leur liberté")
    # 10 | click | id=type |  | 
    self.driver.find_element(By.ID, "type").click()
    # 11 | type | id=type | TV | 
    self.driver.find_element(By.ID, "type").send_keys("TV")
    # 12 | click | id=producer |  | 
    self.driver.find_element(By.ID, "producer").click()
    # 13 | type | id=producer | Sunrise,Bandai,Visual | 
    self.driver.find_element(By.ID, "producer").send_keys("Sunrise,Bandai,Visual")
    # 14 | click | id=studio |  | 
    self.driver.find_element(By.ID, "studio").click()
    # 15 | type | id=studio | Toei,Animation | 
    self.driver.find_element(By.ID, "studio").send_keys("Toei,Animation")
    # 16 | click | css=button |  | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
